---
# tasks file for security
- name: Turn off password login
  replace:
    path: /etc/ssh/sshd_config
    regexp: PasswordAuthentication yes
<<<<<<< HEAD
    replace: PasswordAuthentication no
  tags: [ssh]
=======
    replace: PasswordAuthentication no
>>>>>>> master
