SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRAN
UPDATE Test SET testtext = 'Updated' WHERE id = 1
WAITFOR DELAY '00:00:05'
ROLLBACK

--- 

UPDATE Test SET testtext='999' WHERE id = 1;
---

BEGIN TRANSACTION
INSERT Test Values (4, '444')
COMMIT