apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: osk4r/frontend:v3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer  # ClusterIP, NodePort, ...
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP