---
# tasks file for haproxy

- name: Ensure apache is not installed
  apt:
    name: apache2
    state: absent
  tags: [packages]
- name: Ensure nginx is not installed
  apt:
    name: nginx
    state: absent
  tags: [packages]

- name: Ensure haproxy is present or install it
  apt:
    name: haproxy
    state: present
    update_cache: true
  tags: [packages]

- name: Enable haproxy
  replace: dest=/etc/default/haproxy
              regexp="ENABLED=0"
              replace="ENABLED=1"
  tags: [loadbalancer, config]

- name: Install haproxy config
  template:
    src: templates/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify:
   - Restart Haproxy
  tags: [loadbalancer, config]
