all:
  children:
    webservers:
      hosts:
        35.241.129.189:
        34.76.238.206:
        130.211.99.204:
    loadbalancer:
      hosts:
        34.77.224.149:
    cms:
      hosts:
        34.76.26.43: